Californication/Models/Context.cs
using Microsoft.EntityFrameworkCore;

namespace Californication.Models
{
    public class Context : DbContext
    {
        public Context(DbContextOptions<Context> opcoes) : base(opcoes) { }

        public DbSet<Pessoa> Pessoa { get; set; }
        public DbSet<Produto> Produto { get; set; }
    }
}

Californication/Models/ErrorViewModel.cs
namespace Californication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Californication/Models/Pessoa.cs
using System.ComponentModel.DataAnnotations;

namespace Californication.Models
{
    public class Pessoa
    {
        [Key]
        public int PessoaId { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Profissao { get; set; }

    }
}

Californication/Models/Produto.cs
using System.ComponentModel.DataAnnotations;

namespace Californication.Models
{
    public class Produto
    {
        [Key]
        public int ProdutoId { get; set; }
        public string Nome { get; set; }
        public double Quantidade { get; set; }

    }
}

Californication/Controllers/HomeController.cs
using Californication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Californication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Californication/Controllers/PessoaController.cs
using Californication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Californication.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class PessoaController : Controller
    {
        private readonly Context Context;

        public PessoaController(Context context)
        {
            Context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var pessoas = await Context.Pessoa.ToListAsync();
            return Ok(pessoas);
        }

        [HttpGet("{pessoaId}")]
        public async Task<IActionResult> GetById(int pessoaId)
        {
            return Ok(await Context.Pessoa.FindAsync(pessoaId));
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Insert([FromBody] Pessoa pessoa)
        {
            if(!ModelState.IsValid) return BadRequest(ModelState);

            await Context.Pessoa.AddAsync(pessoa);
            await Context.SaveChangesAsync();

            return Ok(pessoa);
        }

        [HttpPut]
        public async Task<IActionResult> Update([FromBody] Pessoa pessoa)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            Context.Pessoa.Update(pessoa);
            await Context.SaveChangesAsync();

            return Ok(pessoa);
        }

        [HttpDelete("{pessoaId}")]
        public async Task<IActionResult> Delete(int pessoaId)
        {
            var pessoa = await Context.Pessoa.FindAsync(pessoaId);

            Context.Pessoa.Remove(pessoa!);
            await Context.SaveChangesAsync();
            return Ok(true);
        }
    }
}

Californication/Controllers/ProdutoController.cs
using Californication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Californication.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class ProdutoController : Controller
    {
        private readonly Context Context;

        public ProdutoController(Context context)
        {
            Context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var pessoas = await Context.Produto.ToListAsync();
            return Ok(pessoas);
        }

        [HttpGet("{produtoid}")]
        public async Task<IActionResult> GetById(int produtoid)
        {
            return Ok(await Context.Produto.FindAsync(produtoid));
        }

        [HttpPost]
        public async Task<IActionResult> Insert([FromBody] Produto produto)
        {
            if(!ModelState.IsValid) return BadRequest(ModelState);

            await Context.Produto.AddAsync(produto);
            await Context.SaveChangesAsync();

            return Ok(produto);
        }

        [HttpPut]
        public async Task<IActionResult> Update([FromBody] Produto produto)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            Context.Produto.Update(produto);
            await Context.SaveChangesAsync();

            return Ok(produto);
        }

        [HttpDelete("{produtoId}")]
        public async Task<IActionResult> Delete(int produtoId)
        {
            var produto = await Context.Produto.FindAsync(produtoId);

            Context.Produto.Remove(produto!);
            await Context.SaveChangesAsync();
            return Ok(true);
        }
    }
}

Californication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Californication/Views/Pessoa/Index.cshtml
@{
    ViewData["Title"] = "Pessoas Cadastradas";
}

<div class="p-5">
    <div class="border border-light border-3 rounded">
        <div class="container">
            <div class="p-5">
                <div class="row">
                    <div class="col-8">
                        <h6>Pessoas cadastradas</h6>
                    </div>
                    <div class="col-4">
                        <button class="btn btn-sm btn-outline-success novaPessoa">Nova pessoa</button>
                    </div>
                </div>

                <hr />

                <div class="p-5 rounded shadow-sm" id="divTabela">

                </div>

            </div>
        </div>
    </div>
</div>
</div>

<div id="modal" class="modal fade" role="dialog">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title"></h6>
            </div>

            <div class="modal-body">
                <input type="hidden" class="form-control form-control-sm pessoaId" />
                <div class="form-group">
                    <label>Nome</label>
                    <input type="text" class="form-control form-control-sm nome" />
                    <span class="text-danger erroNome d-none"></span>
                </div>

                <div class="form-group">
                    <label>Idade</label>
                    <input type="number" class="form-control form-control-sm idade" />
                    <span class="text-danger erroIdade d-none">Digite um número</span>
                </div>

                <div class="form-group">
                    <label>Profissão</label>
                    <input type="text" class="form-control form-control-sm profissao" />
                    <span class="text-danger erroProfissao d-none">Digite uma profissão</span>
                </div>
            </div>

            <div class="modal-footer">
                <div class="form-group">
                    <input type="button" value="Salvar" class="btn btn-sm btn-outline-success btnSalvar" />
                    <input type="button" value="Cancelar" class="btn btn-sm btn-light" data-bs-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>

</div>

@section scripts {
<script>
    $(document).ready(function () {
        carregarDados();
    });
    function carregarDados() {
        $.ajax({
            url: "GetAll",
            method: "GET",
            success: function (pessoas) {
                montarTabela(pessoas);
            }
        });
    }
    $(".novaPessoa").click(function () {
        escolherTituloModal("Cadastro de nova pessoa");
        mostrarModal();
        limparFormulario();
        $('.pessoaId').val(0);
    });
    $(".btnSalvar").click(function () {
        var pessoa = {
            pessoaId: $('.pessoaId').val(),
            nome: $('.nome').val(),
            idade: $('.idade').val(),
            profissao: $('.profissao').val()
        };
        if (validarFormulario(pessoa)) {
            if (parseInt(pessoa.pessoaId) > 0)
                atualizarPessoa(pessoa);
            criarPessoa(pessoa);
        }
    });
    function criarPessoa(pessoa) {
        $.ajax({
            url: "Insert",
            method: 'POST',
            data: JSON.stringify(pessoa),
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (pessoaCriada) {
                $("#modal").modal('hide');
                var linhaNovaPessoa = `<tr id="${pessoaCriada.pessoaId}">`;
                linhaNovaPessoa += `<td>${pessoaCriada.nome}</td>`;
                linhaNovaPessoa += `<td>${pessoaCriada.idade}</td>`;
                linhaNovaPessoa += `<td>${pessoaCriada.profissao}</td>`;
                linhaNovaPessoa += `<td><button class="btn btn-sm btn-outline-info"
                    onclick="pegarPessoaPeloId(${pessoaCriada.pessoaId})">Atualizar</button> |
                    <button class="btn btn-sm btn-outline-danger"
                    onclick="excluirPessoaPeloId(${pessoaCriada.pessoaId})">Excluir</button></td>`;
                linhaNovaPessoa += '</tr>';
                $(".tabela tbody").append(linhaNovaPessoa);
                limparFormulario();
            }
        });
    }
    function pegarPessoaPeloId(pessoaId) {
        $.ajax({
            url: "GetById/" + pessoaId,
            method: 'GET',
            success: function (pessoa) {
                mostrarModal();
                escolherTituloModal(`Atualizar pessoa ${pessoa.nome}`);
                $(".pessoaId").val(pessoa.pessoaId);
                $(".nome").val(pessoa.nome);
                $(".idade").val(pessoa.idade);
                $(".profissao").val(pessoa.profissao);
            }
        })
    }
    function atualizarPessoa(pessoa) {
        $.ajax({
            url: "Update",
            method: 'PUT',
            data: JSON.stringify(pessoa),
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (pessoaAtualizada) {
                $("#modal").modal('hide');
                var linhaTabela = $(`#${pessoaAtualizada.pessoaId}`);
                linhaTabela[0].childNodes[0].innerText = pessoaAtualizada.nome;
                linhaTabela[0].childNodes[1].innerText = pessoaAtualizada.idade;
                linhaTabela[0].childNodes[2].innerText = pessoaAtualizada.profissao;
                limparFormulario();
            }
        });
    }
    function excluirPessoa(pessoaId) {
        $.ajax({
            url: "Delete/" + pessoaId,
            method: 'DELETE',
            success: function (status) {
                if (status) {
                    alert("Pessoa excluída com sucesso");
                    document.getElementById(pessoaId).remove();
                }
                else
                    alert(status.mensagem);
            }
        })
    }
    function montarTabela(pessoas) {
        var indice = 0;
        var divTabela = document.getElementById("divTabela");
        var tabela = '<table class="table table-sm table-hover table-striped tabela">';
        tabela += '<thead>';
        tabela += '<tr>';
        tabela += '<th>Nome</th>';
        tabela += '<th>Idade</th>';
        tabela += '<th>Profissão</th>';
        tabela += '<th>Ações</th>';
        tabela += '</tr>';
        tabela += '</thead>';
        tabela += '<tbody>';
        for (indice = 0; indice < pessoas.length; indice++) {
            tabela += `<tr id="${pessoas[indice].pessoaId}">`;
            tabela += `<td>${pessoas[indice].nome}</td>`;
            tabela += `<td>${pessoas[indice].idade}</td>`;
            tabela += `<td>${pessoas[indice].profissao}</td>`;
            tabela += `<td><button class="btn btn-sm btn-outline-info" onclick="pegarPessoaPeloId(${pessoas[indice].pessoaId})">Atualizar</button> |
                        <button class="btn btn-sm btn-outline-danger" onclick="excluirPessoa(${pessoas[indice].pessoaId})">Excluir</button></td>`;
            tabela += '</tr>';
        }
        tabela += '</tbody>';
        tabela += '</table>';
        divTabela.innerHTML = tabela;
    }
    function validarFormulario(pessoa) {
        let nomeValido = validarNome(pessoa.nome);
        let idadeValida = validarIdade(pessoa.idade);
        let profissaoValida = validarProfissao(pessoa.profissao);
        if (nomeValido == true && idadeValida == true && profissaoValida == true)
            return true;
        return false;
    }
    function validarNome(nome) {
        let nomeValido = true;
        if (nome.trim() == '' || nome == undefined) {
            $(".nome").addClass('is-invalid');
            $(".erroNome").text("Preencha o nome");
            $(".erroNome").removeClass("d-none");
            nomeValido = false;
        }
        else if (nome.length > 20) {
            $(".nome").addClass('is-invalid');
            $(".erroNome").text("Use menos caracteres");
            $(".erroNome").removeClass("d-none");
            nomeValido = false;
        }
        else {
            $(".nome").removeClass('is-invalid');
            $(".nome").addClass('is-valid');
            $(".erroNome").addClass("d-none");
            nomeValido = true;
        }
        return nomeValido;
    }
    function validarIdade(idade) {
        let idadeValida = true;
        if (isNaN(idade) || idade == undefined || idade == '') {
            $(".idade").addClass('is-invalid');
            $(".erroIdade").text("Preencha a idade");
            $(".erroIdade").removeClass("d-none");
            idadeValida = false;
        }
        else if (parseInt(idade) < 18 || parseInt(idade) > 100) {
            $(".idade").addClass('is-invalid');
            $(".erroIdade").text("Idade inválida");
            $(".erroIdade").removeClass("d-none");
            idadeValida = false;
        }
        else {
            $(".idade").removeClass('is-invalid');
            $(".idade").addClass('is-valid');
            $(".erroIdade").addClass("d-none");
            idadeValida = true;
        }
        return idadeValida;
    }
    function validarProfissao(profissao) {
        let profissaoValida = true;
        if (profissao.trim() == '' || profissao == undefined) {
            $(".profissao").addClass('is-invalid');
            $(".erroProfissao").text("Preencha a profissão");
            $(".erroProfissao").removeClass("d-none");
            profissaoValida = false;
        }
        else if (profissao.length > 50) {
            $(".profissao").addClass('is-invalid');
            $(".erroProfissao").text("Use menos caracteres");
            $(".erroProfissao").removeClass("d-none");
            profissaoValida = false;
        }
        else {
            $(".profissao").removeClass('is-invalid');
            $(".profissao").addClass('is-valid');
            $(".erroProfissao").addClass("d-none");
            profissaoValida = true;
        }
        return profissaoValida;
    }
    function mostrarModal() {
        new bootstrap.Modal($("#modal"), {}).show();
    }
    function limparFormulario() {
        $(".nome").val('');
        $(".nome").removeClass('is-valid');
        $(".idade").val('');
        $(".idade").removeClass('is-valid');
        $(".profissao").val('');
        $(".profissao").removeClass('is-valid');
    }
    function escolherTituloModal(texto) {
        $(".modal-title").text(texto);
    }
</script>
}

Californication/Views/Produto/Index.cshtml
@{
    ViewData["Title"] = "Produtos Cadastrados";
}

<div class="p-5">
    <div class="border border-light border-3 rounded">
        <div class="container">
            <div class="p-5">
                <div class="row">
                    <div class="col-8">
                        <h6>Produtos Cadastrados</h6>
                    </div>
                    <div class="col-4">
                        <button class="btn btn-sm btn-outline-success novoProduto">Novo Produto</button>
                    </div>
                </div>

                <hr />

                <div class="p-5 rounded shadow-sm" id="divTabela">

                </div>

            </div>
        </div>
    </div>
</div>
</div>

<div id="modal" class="modal fade" role="dialog">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title"></h6>
            </div>

            <div class="modal-body">
                <input type="hidden" class="form-control form-control-sm produtoId" />
                <div class="form-group">
                    <label>Nome</label>
                    <input type="text" class="form-control form-control-sm nome" />
                    <span class="text-danger erroNome d-none"></span>
                </div>

                <div class="form-group">
                    <label>Quantidade</label>
                    <input type="number" class="form-control form-control-sm quantidade" />
                    <span class="text-danger erroQuantidade d-none">Digite um número</span>
                </div>
            </div>

            <div class="modal-footer">
                <div class="form-group">
                    <input type="button" value="Salvar" class="btn btn-sm btn-outline-success btnSalvar" />
                    <input type="button" value="Cancelar" class="btn btn-sm btn-light" data-bs-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>

</div>

@section scripts {
<script>
    $(document).ready(function () {
        carregarDados();
    });
    function carregarDados() {
        $.ajax({
            url: "GetAll",
            method: "GET",
            success: function (produtos) {
                montarTabela(produtos);
            }
        });
    }
    $(".novoProduto").click(function () {
        escolherTituloModal("Cadastro de novo produto");
        mostrarModal();
        limparFormulario();
        $('.produtoId').val(0);
    });
    $(".btnSalvar").click(function () {
        var produto = {
            produtoId: $('.produtoId').val(),
            nome: $('.nome').val(),
            quantidade: $('.quantidade').val()
        };
        if (validarFormulario(produto)) {
            if (parseInt(produto.produtoId) > 0)
                atualizarProduto(produto);
            criarProduto(produto);
        }
    });
    function criarProduto(produto) {
        $.ajax({
            url: "Insert",
            method: 'POST',
            data: JSON.stringify(produto),
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (produtoCriada) {
                $("#modal").modal('hide');
                var linhaNovaProduto = `<tr id="${produtoCriada.produtoId}">`;
                linhaNovaProduto += `<td>${produtoCriada.nome}</td>`;
                linhaNovaProduto += `<td>${produtoCriada.quantidade}</td>`;
                linhaNovaProduto += `<td><button class="btn btn-sm btn-outline-info"
                    onclick="pegarProdutoPeloId(${produtoCriada.produtoId})">Atualizar</button> |
                    <button class="btn btn-sm btn-outline-danger"
                    onclick="excluirProdutoPeloId(${produtoCriada.produtoId})">Excluir</button></td>`;
                linhaNovaProduto += '</tr>';
                $(".tabela tbody").append(linhaNovaProduto);
                limparFormulario();
            }
        });
    }
    function pegarProdutoPeloId(produtoId) {
        $.ajax({
            url: "GetById/" + produtoId,
            method: 'GET',
            success: function (produto) {
                mostrarModal();
                escolherTituloModal(`Atualizar produto ${produto.nome}`);
                $(".produtoId").val(produto.produtoId);
                $(".nome").val(produto.nome);
                $(".quantidade").val(produto.quantidade);
            }
        })
    }
    function atualizarProduto(produto) {
        $.ajax({
            url: "Update",
            method: 'PUT',
            data: JSON.stringify(produto),
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (produtoAtualizada) {
                $("#modal").modal('hide');
                var linhaTabela = $(`#${produtoAtualizada.produtoId}`);
                linhaTabela[0].childNodes[0].innerText = produtoAtualizada.nome;
                linhaTabela[0].childNodes[1].innerText = produtoAtualizada.quantidade;
                limparFormulario();
            }
        });
    }
    function excluirProduto(produtoId) {
        $.ajax({
            url: "Delete/" + produtoId,
            method: 'DELETE',
            success: function (status) {
                if (status) {
                    alert("Produto excluída com sucesso");
                    document.getElementById(produtoId).remove();
                }
                else
                    alert(status.mensagem);
            }
        })
    }
    function montarTabela(produtos) {
        var indice = 0;
        var divTabela = document.getElementById("divTabela");
        var tabela = '<table class="table table-sm table-hover table-striped tabela">';
        tabela += '<thead>';
        tabela += '<tr>';
        tabela += '<th>Nome</th>';
        tabela += '<th>Quantidade</th>';
        tabela += '<th>Ações</th>';
        tabela += '</tr>';
        tabela += '</thead>';
        tabela += '<tbody>';
        for (indice = 0; indice < produtos.length; indice++) {
            tabela += `<tr id="${produtos[indice].produtoId}">`;
            tabela += `<td>${produtos[indice].nome}</td>`;
            tabela += `<td>${produtos[indice].quantidade}</td>`;
            tabela += `<td><button class="btn btn-sm btn-outline-info" onclick="pegarProdutoPeloId(${produtos[indice].produtoId})">Atualizar</button> |
                        <button class="btn btn-sm btn-outline-danger" onclick="excluirProduto(${produtos[indice].produtoId})">Excluir</button></td>`;
            tabela += '</tr>';
        }
        tabela += '</tbody>';
        tabela += '</table>';
        divTabela.innerHTML = tabela;
    }
    function validarFormulario(produto) {
        let nomeValido = validarNome(produto.nome);
        let quantidadeValida = validarQuantidade(produto.quantidade);
        if (nomeValido == true && quantidadeValida == true)
            return true;
        return false;
    }
    function validarNome(nome) {
        let nomeValido = true;
        if (nome.trim() == '' || nome == undefined) {
            $(".nome").addClass('is-invalid');
            $(".erroNome").text("Preencha o nome");
            $(".erroNome").removeClass("d-none");
            nomeValido = false;
        }
        else if (nome.length > 20) {
            $(".nome").addClass('is-invalid');
            $(".erroNome").text("Use menos caracteres");
            $(".erroNome").removeClass("d-none");
            nomeValido = false;
        }
        else {
            $(".nome").removeClass('is-invalid');
            $(".nome").addClass('is-valid');
            $(".erroNome").addClass("d-none");
            nomeValido = true;
        }
        return nomeValido;
    }
    function validarQuantidade(quantidade) {
        let quantidadeValida = true;
        if (isNaN(quantidade) || quantidade == undefined || quantidade == '') {
            $(".quantidade").addClass('is-invalid');
            $(".erroQuantidade").text("Preencha a quantidade");
            $(".erroQuantidade").removeClass("d-none");
            quantidadeValida = false;
        }
        else if (parseInt(quantidade) < 0) {
            $(".quantidade").addClass('is-invalid');
            $(".erroQuantidade").text("Quantidade inválida");
            $(".erroQuantidade").removeClass("d-none");
            quantidadeValida = false;
        }
        else {
            $(".quantidade").removeClass('is-invalid');
            $(".quantidade").addClass('is-valid');
            $(".erroQuantidade").addClass("d-none");
            quantidadeValida = true;
        }
        return quantidadeValida;
    }
    function mostrarModal() {
        new bootstrap.Modal($("#modal"), {}).show();
    }
    function limparFormulario() {
        $(".nome").val('');
        $(".nome").removeClass('is-valid');
        $(".quantidade").val('');
        $(".quantidade").removeClass('is-valid');
    }
    function escolherTituloModal(texto) {
        $(".modal-title").text(texto);
    }
</script>
}

Californication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UCS Manager</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Californication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UCS Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Californication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>